{% set name = "h5grove" %}
{% set version = "2.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/h5grove-{{ version }}.tar.gz
  sha256: 4ff4aed7166931ed71466ebe6ef49871a8ae76d85e4084601362c8a2b7af0c5d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - numpy
    - orjson
    - h5py >=3
    - tifffile
    - typing-extensions

test:
  imports:
    - h5grove
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/silx-kit/h5grove
  summary: Core utilities to serve HDF5 file contents
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - t20100
    - loichuder
