{% set name = "h5grove" %}
{% set version = "2.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/h5grove-{{ version }}.tar.gz
  sha256: 8d438f2a4616d64b176e6ff352d23b39027b9f1ab2c9169fcfd6f5f1caca8728

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - numpy
    - orjson
    - h5py >=3
    - tifffile
    - typing-extensions

test:
  imports:
    - h5grove
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/silx-kit/h5grove
  summary: Core utilities to serve HDF5 file contents
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - t20100
    - loichuder
